name: weixin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # 无sudo时区方案，不会报权限错
      - name: 设置上海时区
        run: echo "TZ=Asia/Shanghai" >> $GITHUB_ENV

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weixin send script
        env:
          WX_APP_ID: ${{ secrets.WX_APP_ID }}
          WX_APP_SECRET: ${{ secrets.WX_APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_OPENID: ${{ secrets.USER_OPENID }}
          CITY: ${{ secrets.CITY }}
        run: python3 main.py
